<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>


	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
		<PackageReference Include="Syncfusion.Blazor.Cards" />
		<PackageReference Include="Syncfusion.Blazor.DataForm" />
		<PackageReference Include="Syncfusion.Blazor.Grid" />
		<PackageReference Include="Syncfusion.Blazor.Inputs" />
		<PackageReference Include="Syncfusion.Blazor.Notifications" />
		<PackageReference Include="Syncfusion.Blazor.RichTextEditor" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MapQuest.Client.Gps\MapQuest.Client.Gps.csproj" />
		<ProjectReference Include="..\MapQuest.Client.HtmlEditor\MapQuest.Client.HtmlEditor.csproj" />
		<ProjectReference Include="..\MapQuest.Client.Interfaces\MapQuest.Client.Interfaces.csproj" />
		<ProjectReference Include="..\MapQuest.Geo\MapQuest.Geo.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\" />
	</ItemGroup>

</Project>
